image: ubuntu:22.04
variables:
  DEBIAN_FRONTEND: noninteractive
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- builds
- tests

.build:
  stage: builds
  before_script:
  - apt -qqy update
  - apt -y install wget gzip curl build-essential
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  script:
  - source $HOME/.cargo/env
  - cargo build
  artifacts:
    paths:
    - target/debug/trace2power
    - Cargo.lock

build_debug:
  extends: .build
  script:
  - source $HOME/.cargo/env
  - cargo build
  artifacts:
    paths:
    - target/debug/trace2power
    - Cargo.lock

build_release:
  extends: .build
  script:
  - source $HOME/.cargo/env
  - cargo build --release
  artifacts:
    paths:
    - target/release/trace2power
    - Cargo.lock

.test:
  stage: tests
  before_script:
  - apt -qqy update &> /dev/null
  - apt -y install gzip tar build-essential iverilog time
  artifacts:
    when: always
    paths:
    - tests/*/out.saif
    - tests/*/out.tcl

test_debug:
  extends: .test
  script:
  - export EXAMPLES_DIRECTORY=$(pwd)/examples
  - export PATH=$PATH:$(pwd)/target/debug
  - make -C tests
  dependencies: [build_debug]

test_release:
  extends: .test
  script:
  - export EXAMPLES_DIRECTORY=$(pwd)/examples
  - export PATH=$PATH:$(pwd)/target/release
  - make -C tests
  dependencies: [build_release]
