# Copyright (c) 2025-2026 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

all:
	$(MAKE) -C counter
	$(MAKE) -C glitch
	$(MAKE) -C hierarchical
	$(MAKE) -C peak_power
	$(MAKE) -C synth
	$(MAKE) -C tail
	$(MAKE) -C tristate
